In [1]:
import numpy as np

In [ ]:
# Scalars and Vectors 

scalar = 420 #Scalar is just a single value


In [16]:


vector = [1,2,3] #vector is just a 1D array

# adding vectors 

v1 = np.array([1,2,3])

v2 = np.array([4,5,6])

result = v1+v2

result # [5, 7, 9]



array([5, 7, 9])

In [17]:


# Subtract the vectors

result2 = v1-v2

result2 # [-3,-3,-3]


array([-3, -3, -3])

In [18]:


# Dot product of two vectors

dot_product = np.dot(v1,v2)

dot_product # Represents the alignment or similarity in direction between two vectors in a high-dimensional space.


32

In [19]:
#Cosine similarity

magnitude_v1 = np.linalg.norm(v1)

magnitude_v2 = np.linalg.norm(v2)

# Calculate the cosine similarity
cosine_similarity = dot_product / (magnitude_v1 * magnitude_v2)

cosine_similarity

0.9746318461970762

In [20]:

# Cross product of two vectors
cross_product = np.cross(v1, v2)
cross_product

array([-3,  6, -3])