In [209]:
import numpy as np

### The Basics

In [211]:
# The Basics
x = np.array([1,2,3,4])
print(x)

a = np.array([[1.0,20.0],[90.0,100.0]])
print(a)

# Specify Data Type
b = np.array([[1,2],[3,4],[5,6]],dtype="int16")
print(b)

[1 2 3 4]
[[  1.  20.]
 [ 90. 100.]]
[[1 2]
 [3 4]
 [5 6]]


In [212]:
# Get Dimension
a.ndim

2

In [213]:
# Get Shape
a.shape

(2, 2)

In [214]:
# Get Type
b.dtype

dtype('int16')

In [215]:
# Get Single Item Size (in bytes)
b.itemsize

2

In [216]:
# Get Length
b.size

6

In [217]:
# Get total item size (in bytes)
b.nbytes

12

### Accessing/Changing specific elements, rows, columns, etc

In [219]:


# Accessing second row first column of 'b'
print(b[1,0])

3


In [220]:
#Get A Specific Row

b[2,:]

array([5, 6], dtype=int16)

In [221]:
#Get A Specific Column

b[:,1]

array([2, 4, 6], dtype=int16)

In [222]:
# Get Range Of Numbers [start index, end index, step size]
x[1:3:1]

array([2, 3])

In [223]:
# Replace column

b[:,1] = 10
b

array([[ 1, 10],
       [ 3, 10],
       [ 5, 10]], dtype=int16)

In [224]:
# Replace row

b[0,:] = 20
b

# We can also do this
b[1,:] = [420,520]

b

array([[ 20,  20],
       [420, 520],
       [  5,  10]], dtype=int16)

In [225]:
# 3D Example

c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [226]:
# Acessing first row of the first row 
c[0,:][0,:]

array([1, 2, 3])

In [227]:
c[:,0,:]

array([[1, 2, 3],
       [7, 8, 9]])

### Initializing Different Types Of Arrays

In [229]:


# All 0s Matrix
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [230]:
# All 1s Matrix
np.ones((4,2,2),dtype="int32")

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [231]:
# Any other number
np.full((2,2),99,dtype="int8")

array([[99, 99],
       [99, 99]], dtype=int8)

In [232]:

# Random Decimal Numbers
np.random.rand(4,2,3)

array([[[0.20851569, 0.42572112, 0.08571289],
        [0.38305784, 0.86643469, 0.96892915]],

       [[0.32588346, 0.40822442, 0.68968121],
        [0.41872156, 0.97228874, 0.53816258]],

       [[0.16277389, 0.72259841, 0.20989622],
        [0.61583551, 0.12714588, 0.62010274]],

       [[0.73419299, 0.52927294, 0.8904246 ],
        [0.74908197, 0.79981929, 0.95887186]]])

In [233]:

# Random Integer Values (StartValue,size)

np.random.randint(1,100,size = (3,3))

array([[62, 11, 27],
       [43, 76, 29],
       [21, 57,  9]])

In [234]:

# The Identity Matrix

np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [235]:
# Repeat an array (array,repeat time,axis (optional))

arr = np.array([[1,2,4]])

r1 = np.repeat(arr,10,axis = 0)
r1

array([[1, 2, 4],
       [1, 2, 4],
       [1, 2, 4],
       [1, 2, 4],
       [1, 2, 4],
       [1, 2, 4],
       [1, 2, 4],
       [1, 2, 4],
       [1, 2, 4],
       [1, 2, 4]])

#### Exercise 

In [237]:


output = np.ones((5,5),dtype="int8")
output[1,:] = [1,0,0,0,1]
output[2,:] = [1,0,9,0,1]
output[-2,:] = [1,0,0,0,1]
output


array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

### Be Careful When Copying Arrays!!!

In [239]:
a = np.array([1,2,3])
b = a
b[0]= 100
print(b)
print(a)

#Do this instead
c = a.copy()
c[0] = 200
print(c)
print(a)

[100   2   3]
[100   2   3]
[200   2   3]
[100   2   3]


### Mathematics

In [241]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [242]:
a+2

array([3, 4, 5, 6, 7])

In [243]:
a -= 2
a

array([-1,  0,  1,  2,  3])

In [244]:
a*5

array([-5,  0,  5, 10, 15])

In [245]:
a/3

array([-0.33333333,  0.        ,  0.33333333,  0.66666667,  1.        ])

In [246]:
# Adding Two Vectors
b = [10,20,30,40,50]

a+b

array([ 9, 20, 31, 42, 53])

In [247]:
# Take the sin/cos of all values
np.sin(b)
np.cos(a)

array([ 0.54030231,  1.        ,  0.54030231, -0.41614684, -0.9899925 ])

#### Linear Algebra

##### Multiplication

In [250]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

np.matmul(a,b)


[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

#### Determinant

In [252]:
a = np.full((4,4),9)
c = np.linalg.det(a)
c

0.0

In [253]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

### Statistics

In [255]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [256]:
# Finding the min
np.min(stats)

1

In [257]:
# Finding the max
np.max(stats)

6

In [258]:
# Summing
np.sum(stats)

21

### Reorganizing Arrays

In [260]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


#### Vertically Stacking Vectors

In [305]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

#### Horizontal Stacking Vectors

In [310]:
np.hstack([v1,v2])

array([1, 2, 3, 4, 5, 6, 7, 8])

### Miscellaneous

#### Load Data From File

In [322]:
arr = np.genfromtxt('data.txt',delimiter=",")
arr = arr.astype("int32")
arr

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

#### Boolean Masking and Advanced Indexing

In [341]:
arr > 100

(~((arr>=100) & (arr<1000)))

array([[ True,  True,  True,  True, False,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True]])

In [327]:
# Getting values > 50
arr[arr>50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [331]:
# You can index with a list in NumPy
d = np.array([1,2,3,4,5,6])
d[[1,2,-1]]

array([2, 3, 6])

### Exercise

In [344]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [352]:
arr[2:4,0:2]

array([[11, 12],
       [16, 17]])

In [357]:
arr[[0,4,5],3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])